@StandAPI_HostAddress = http://localhost:5163

### Listar todos os veículos
GET {{StandAPI_HostAddress}}/api/veiculos
Accept: application/json

### Adicionar um novo veículo
POST {{StandAPI_HostAddress}}/api/veiculos
Content-Type: application/json

### Atualizar parcialmente um veiculo
PUT {{StandAPI_HostAddress}}/api/veiculos/{{matricula}}

### Eliminar um veiculo
DELETE {{StandAPI_HostAddress}}/api/veiculos/{{matricula}}
